### ISSUE TITLE
Add Query Labels

### ISSUE THREAD

**Issue by andgorrie** [scalyr/scalyr-grafana-datasource-plugin#105]
This new version (DataSet vs Scalyr) of the plugin does not seem to allow me to label my Queries.  If I add two or more Queries in the chart they are shown as "Value".  In the old plugin I used the "Label" textbox to label them. It looks like you intend me to use a breakdown, but in most of my use cases I don't want to and just need it to count the matches for the expression.

New:
![image](https://user-images.githubusercontent.com/11076582/174156695-54772045-8135-4650-8856-7be6a2be605b.png)

Old:
![image](https://user-images.githubusercontent.com/11076582/174156862-46371941-f517-473c-8d69-6a3aded26a5b.png)

**Comment by jmakar-scalyr** [comment]
Thanks for bringing this up, it will be included in the upcoming 3.0.5 release
