### ISSUE TITLE
TypeError: Cannot assign to read only property 'scalyrUrl' of object '#<Object>'

### ISSUE THREAD

**Issue by driedener** [scalyr/scalyr-grafana-datasource-plugin#124]
When trying to add or edit a dataset datasource in the actual Grafana Cloud version, it's throwing an error. Reproducible on multiple machines and stacks.

Grafana: 10.2.0-60139
Plugin Version: 3.1.2

**Comment by weilliu** [comment]
@driedener I was able to reproduce the same issue locally. Let me check with engineering and get back to you

**Comment by ImraanGoonner** [comment]
Hi there, any update on the issue. Seems all versions impacted

**Comment by jmakar-scalyr** [comment]
Investigating, will get back to you shortly

**Comment by jmakar-scalyr** [comment]
This is fixed in release 3.1.3

It only affects Grafana cloud installations so we have to wait (hopefully not long) until the release gets approved by Grafana support before it will be available to cloud installations

**Comment by driedener** [comment]
Great, the fix ist available on Grafana Cloud.

**Comment by carlmagnusholmstrom-tomtom** [comment]
Can confirm that it works again with release 3.1.3
