### ISSUE TITLE
README.md shipped as part of plugin cannot have relative image links per grafana

### ISSUE THREAD

**Issue by lakshmi-kannan** [scalyr/scalyr-grafana-datasource-plugin#23]
See https://grafana.com/docs/plugins/developing/plugin-review-guidelines/#readme-md. 

Our graphs PNGs therefore don't render. It would be good to create an alternate README.md that just points to github README.md or a blog post.

**Comment by joseph-makar** [comment]
This is resolved by using https://raw.githubusercontent.com/scalyr/scalyr-grafana-datasource-plugin/master/... to link to images (suggestion from Grafana support)
