### ISSUE TITLE
Add to Grafana Plugin Page

### ISSUE THREAD

**Issue by chadleeshaw** [scalyr/scalyr-grafana-datasource-plugin#37]
Just a nice to have!

Currently this plugin isn't listed on Grafana's plugin page:
https://grafana.com/grafana/plugins?orderBy=weight&direction=asc

This makes adding this plugin via environment variable or Grafana cli impossible.  Would love to add via Docker startup with:
GF_INSTALL_PLUGINS={{ Insert Project Name }}

**Comment by harrisonScalyr** [comment]
Thanks @chadleeshaw We'll add this to our roadmap. Will update once we have a timeline.

**Comment by makaveli0129** [comment]
It's really simple to add it to their site https://github.com/grafana/grafana-plugin-repository

**Comment by joseph-makar** [comment]
This is resolved, https://grafana.com/grafana/plugins/sentinelone-dataset-datasource/

Be aware that a new version of plugin (3.0.4) is available that is still in the Grafana approval process but is available as a release here.
