### ISSUE TITLE
Add support for missing graph functions

### ISSUE THREAD

**Issue by ReinAchten-TomTom** [scalyr/scalyr-grafana-datasource-plugin#55]
The current data source does not support all [graph functions](https://app.scalyr.com/help/query-language#graphFunctions) which limits the graphing functionality. Specifically, `sum`, Nth percentile and `fraction` are missing. Especially missing `fraction(expr)` is limiting; right now it's just not possible to graph e.g. error percentages. Please add support for all missing graph functions.

**Comment by joseph-makar** [comment]
With the new plugin implementation (available [here](https://grafana.com/grafana/plugins/sentinelone-dataset-datasource/)) this can be done with standard or power queries (I'm new to the query languages so I didn't use fraction directly):

![20220608T081324](https://user-images.githubusercontent.com/103437771/172614770-f3a27412-580a-4e0d-9dc3-ec87f70db83a.png)

![20220608T081130](https://user-images.githubusercontent.com/103437771/172614808-9d7f45a1-8eb1-40f4-ba1d-0ffb1bc25117.png)
