### ISSUE TITLE
Add support for complex expressions

### ISSUE THREAD

**Issue by ReinAchten-TomTom** [scalyr/scalyr-grafana-datasource-plugin#56]
[Complex expressions](https://app.scalyr.com/help/query-language#complexExpressions) provide significant graphing freedom. Such complex expressions, even though part of Scalyr' query language are currently not supported by the data source. Please add support for these complex expressions.

**Comment by joseph-makar** [comment]
This is supported by the new plugin implementation (available [here](https://grafana.com/grafana/plugins/sentinelone-dataset-datasource/))

![20220608T082715](https://user-images.githubusercontent.com/103437771/172616323-b56e6ade-8361-4230-83aa-8e22b52c8b8c.png)
