### ISSUE TITLE
Provide releases as ZIP archives as well

### ISSUE THREAD

**Issue by ReinAchten-TomTom** [scalyr/scalyr-grafana-datasource-plugin#61]
grafana-cli, which is a commonly used tool to install plugins not coming from grafana.com, requires a ZIP archive. Quoting the grafana-cli usage:
```
   --pluginUrl value        Full url to the plugin zip file instead of downloading the plugin from grafana.com/api [$GF_PLUGIN_URL]
```
Having only a .tar.gz available hampers installation. Please provide releases as ZIP archives going forward and either publish a new release or add ZIP files to existing releases in hindsight.

**Comment by MarcoMusso-TomTom** [comment]
It seems that the v2.2.0 zip files is affected by the same problem of v2.1.0 (ie installing the tar.gz works, zip file doesn't).

**Comment by yanscalyr** [comment]
The new 2.3.0 release has an associated zip file, as will releases going forward. The `README.md` has also been updated with instructions for installing via grafana-cli with the appropriate `--pluginUrl` value, can be found [here].(https://github.com/scalyr/scalyr-grafana-datasource-plugin#installing-with-grafana-cli)

**Comment by yanscalyr** [comment]
I am closing this issue, please reopen if necessary.
